### ISSUE TITLE
Problems building with xcaddy

### ISSUE THREAD

**Issue by nrfox** [caddy-dns/namecheap#2]
As a follow up to #1, even after merging the fix, trying to build with xcaddy fails with the same `module declares its path as: namecheap-dns...` error. Clearing the go mod cache does not fix the problem however disabling the goproxy and then running `xcaddy build ...` did work. There may be some issue with the default goproxy caching a bad version of this library.

As a workaround for now
1. Disable the goproxy for the namecheap lib
```
export GONOPROXY="namecheap"
```
2. Clear local go mod cache
```
go clean -modcache
```

Then try running `xcaddy build ...` again

**Comment by ghost64** [comment]
I have just tested and it works fine but I am using docker to build it so I would not have a cache at all.

**Comment by nrfox** [comment]
Testing again the build succeeds without the extra flags. The [goproxy](https://proxy.golang.org/) must've just taken a few minutes to update with the latest version. Thanks again for the patch! Closing this issue.
