### ISSUE TITLE
Is this not an officially supported module?

### ISSUE THREAD

**Issue by gregs007** [caddy-dns/namecheap#7]
caddy add-package reports: 
"github.com/caddy-dns/namecheap is not a registered Caddy module package path"

It's also not on caddyserver.com for download.

**Comment by nrfox** [comment]
Thanks for the nudge. I have claimed the listing and running `caddy add-package github.com/caddy-dns/namecheap` completed successfully.

**Comment by mholt** [comment]
Hurray! Thanks for doing that :)
